[package]
name = "image"
version = "0.23.0"
edition = "2018"
license = "MIT"
description = "Imaging library written in Rust. Provides basic filters and decoders for the most common image formats."
authors = ["The image-rs Developers"]
readme = "README.md"
documentation = "https://docs.rs/image"
repository = "https://github.com/image-rs/image"
homepage = "https://github.com/image-rs/image"
categories = ["multimedia::images", "multimedia::encoding"]
exclude = [
    "src/png/testdata/*",
    "examples/*",
    "tests/*",
]

[lib]
name = "image"
path = "./src/lib.rs"

[dependencies]
bytemuck = "1"
byteorder = "1.3.2"
num-iter = "0.1.32"
num-rational = { version = "0.2.1", default-features = false }
num-traits = "0.2.0"
gif = { version = "0.10.0", optional = true }
jpeg = { package = "jpeg-decoder", version = "0.1", default-features = false, optional = true }
png = { version = "0.15.2", optional = true }
scoped_threadpool = { version = "0.1", optional = true }
tiff = { version = "0.4.0", optional = true }
libwebp = { git = "https://github.com/afc11hn/webp.git", optional = true, package = "webp" }

[dev-dependencies]
crc32fast = "1.2.0"
num-complex = "0.2.0"
glob = "0.3"
quickcheck = "0.9"
criterion = "0.3"

[features]
default = ["gif", "jpeg", "ico", "png", "pnm", "tga", "tiff", "webp", "bmp", "hdr", "dxt", "dds", "jpeg_rayon", "libwebp"]

ico = ["bmp", "png"]
pnm = []
tga = []
webp = []
bmp = []
hdr = ["scoped_threadpool"]
dxt = []
dds = ["dxt"]
jpeg_rayon = ["jpeg/rayon"]

benchmarks = []

[[bench]]
path = "benches/encode_bmp.rs"
name = "BMPEncoder"
harness = false
